# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

# HODL username
username: rapax # < TU_USUARIO@hodl.ar

# NOSTR Settings
nostr: # Sin el # adelante
  npub: npub1zrl8uvj2myhfrgkfzkf5hx35nlpp69w3n43c4ds769dlvhxeh80sexgael # Entre comillas dobles

# Configuración Global
html:
# title: Este valor no funciona porque esta comentado
  title: Links | Gaspar Pelayo # Este es el Título que aparece en la pestaña de navegador

# Colores de plantilla
theme:
  background_color: "#f9fafb"
  # cover_color: "#ff7070"

# Configuración Central
main:
  title: Gaspar (Rapax) Pelayo # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  - title: Twitter
    icon: twitter
    url: https://twitter.com/rapax00
  
  - title: LinkedIn
    icon: linkedin
    url: https://www.linkedin.com/in/gaspar-pelayo

  - title: Github
    icon: github
    url: https://github.com/rapax00
  
  - title: Nostr
    icon: nostr
    url: https://iris.to/rapax@hodl.ar

  - title: Telegram
    icon: telegram
    url: https://t.me/rapax00
